### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by 2bWant2b** [xkloveme/utools-desktop-cloud#1]
输入123456后无法登录，不知道是什么原因呢？

**Comment by xkloveme** [comment]
此为单机版,需要登录注册的话[https://static-fb13c39a-ce5d-4fbc-9fe5-96360b09fdec.bspapp.com/utools/#/](https://static-fb13c39a-ce5d-4fbc-9fe5-96360b09fdec.bspapp.com/utools/#/)
